apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aso2
  namespace: azure-service-operator-system
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
---
# HelmRelease for the ingress-nginx chart
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-service-operator
  namespace: azure-service-operator-system
spec:
  interval: 1m0s
  
  # enable drift detection
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]

  chart:
    spec:
      chart: azure-service-operator
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: azure-service-operator-system
      version: "2.13.0" # specify the version you want to use
  
  values: # ingress class name ingress-internal, default
    crdPattern: 'resources.azure.com/*;containerservice.azure.com/*;'
